services:
  web:
    build:
      context: .
    volumes:
      - ./vektors:/vektors
      - media:/vektors/mediafiles
      - static:/vektors/staticfiles
    env_file:
      - ./vektors/.env
    expose:
      - 8000
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py createsuperuser --noinput &&
             gunicorn -w 5 -b 0.0.0.0:8000 vektors.wsgi"

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./vektors/.env

  redis:
    image: redis:7.0.5
    hostname: redis

  celery:
    build:
      context: .
    command: celery -A vektors worker -l info
    volumes:
      - ./vektors:/vektors
    env_file:
      - ./vektors/.env
    links:
      - redis
    depends_on:
      - redis
      - database

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - media:/vektors/mediafiles
      - static:/vektors/staticfiles
      - ./ssl/dikerman.crt:/etc/nginx/dikerman.crt
      - ./ssl/dikerman.key:/etc/nginx/dikerman.key
      - ./ssl/ca.crt:/etc/nginx/ca.crt
    depends_on:
      - web


volumes:
  postgres-data:
  static:
  media: