services:
  web:
    build:
      context: .
    volumes:
      - ./vektors:/vektors
      - media:/vektors/mediafiles
      - static:/vektors/staticfiles
    env_file:
      - ./vektors/.env
    expose:
      - 8000
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py createsuperuser --noinput &&
             gunicorn -w 5 -b 0.0.0.0:8000 vektors.wsgi"

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./vektors/.env

  redis:
    image: redis:7.0.5
    hostname: redis

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - media:/vektors/mediafiles
      - static:/vektors/staticfiles
    depends_on:
      - web

volumes:
  postgres-data:
  static:
  media: