services:
  web:
    build:
      context: .
    volumes:
      - ./vektors:/vektors
      - media:/vektors/mediafiles
      - static:/vektors/staticfiles
    env_file:
      - ./vektors/.env
    expose:
      - 8000
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn -w 5 -b 0.0.0.0:8000 vektors.wsgi"

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./vektors/.env

volumes:
  postgres-data:
  static:
  media: