# Generated by Django 4.2.11 on 2024-03-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('picture', models.FileField(upload_to='media/upload/main/', verbose_name='Выберите картинку')),
            ],
            options={
                'verbose_name': 'Картинка для оформления',
                'verbose_name_plural': 'Картинки для оформления',
            },
        ),
    ]
