# Generated by Django 4.2.11 on 2024-03-14 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_pictures_lessonadditionalvideo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonadditionalpicture',
            name='related_lesson',
        ),
        migrations.RemoveField(
            model_name='lessonadditionalvideo',
            name='related_lesson',
        ),
        migrations.AddField(
            model_name='lessonadditionalpicture',
            name='p_related_lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='p_related_lessons', to='lessons.lesson', verbose_name='урок'),
        ),
        migrations.AddField(
            model_name='lessonadditionalvideo',
            name='v_related_lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='v_related_lessons', to='lessons.lesson', verbose_name='урок'),
        ),
    ]
