# Generated by Django 4.2.11 on 2024-03-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_remove_lessonadditionalpicture_related_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonadditionalvideo',
            name='name',
            field=models.CharField(default='some name', max_length=150, verbose_name='Название видео'),
            preserve_default=False,
        ),
    ]
